name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.58.3'
    - name: Build website
      run: hugo --minify
    - name: Authenticate at GCP Dev
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v2
    - name: gcloud Set up
      run: gcloud config set project ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
    - name: Upload files to samedguener.com
      run: gsutil -m cp -r public/* gs://samedguener.com/
    - name: Upload files to samedguener.de
      run: gsutil -m cp -r public/* gs://samedguener.de/
